In [ ]:
import numpy as np

In [ ]:
def iterateWithSOR(initialGrid, unknownNodes, w, h, g, K):
  currentGrid = initialGrid.astype(float)
  for k in range(K):
    pastGrid = currentGrid
    # print(f'Past grid at iteration {k}:')
    # print(pastGrid)
    for unknownNode in unknownNodes:
      x, y = unknownNode
      # print(f'currentGrid[{x}][{y}] = {pastGrid[x][y]}'
      #   + f'+ ({w/4})*('
      #   + f'{pastGrid[x+1][y]} '
      #   + f'+ {currentGrid[x-1][y]} '
      #   + f'+ {currentGrid[x][y-1]} '
      #   + f'+ {pastGrid[x][y+1]} '
      #   + f'+ {-4*pastGrid[x][y]} '
      #   + f'-{h**2}*{g(x,y)}'
      #   + f') = {pastGrid[x][y] + (w/4)*(pastGrid[x+1][y]+ currentGrid[x-1][y]+ currentGrid[x][y-1]+ pastGrid[x][y+1] -4*pastGrid[x][y] -h**2*g(x,y))}'
      # )
      currentGrid[x][y] = pastGrid[x][y]\
        + (w/4)*(\
          pastGrid[x+1][y]\
          + currentGrid[x-1][y]\
          + currentGrid[x][y-1]\
          + pastGrid[x][y+1]\
          -4*pastGrid[x][y]\
          -g(x,y,h)\
        )
  print(f'Current grid at iteration {k}:')
  print(currentGrid)

# Ex 3.4

In [ ]:
h = 1/4

def g(x,y,h):
  return -h**2*x*h*(y*h-1)/(9e-3)

##SOR Method

In [ ]:
initialGrid = np.array(
    [
    [-5,-10,-10,-10,5],
    [0,-5,-7,5,20],
    [0,5,10,15,20],
    [0,5,7,15,20],
    [5,10,10,10,15]
    ]
)
zerosInitialGrid = np.array(
    [
    [-5,-10,-10,-10,5],
    [0,-0,0,0,20],
    [0,0,0,0,20],
    [0,0,0,0,20],
    [5,10,10,10,15]
    ]
)
unknownNodes = [
    (1,1),(2,1),(3,1),
    (1,2),(2,2),(3,2),
    (1,3),(2,3),(3,3)
]

##w = 1

In [ ]:
w = 1
iterateWithSOR(zerosInitialGrid, unknownNodes, w, h, g, 50)

Current grid at iteration 49:
[[ -5.         -10.         -10.         -10.           5.        ]
 [  0.          -3.22792659  -1.6827877    4.31795635  20.        ]
 [  0.           0.07316468   3.046875     9.38864087  20.        ]
 [  0.           3.07787698   6.14459325  11.0577877   20.        ]
 [  5.          10.          10.          10.          15.        ]]


##w = 1.25

In [ ]:
w = 1.25
iterateWithSOR(zerosInitialGrid, unknownNodes, w, h, g, 44)

Current grid at iteration 43:
[[ -5.         -10.         -10.         -10.           5.        ]
 [  0.          -3.22792659  -1.6827877    4.31795635  20.        ]
 [  0.           0.07316468   3.046875     9.38864087  20.        ]
 [  0.           3.07787698   6.14459325  11.0577877   20.        ]
 [  5.          10.          10.          10.          15.        ]]


##w = 1.5

In [ ]:
w = 1.5
iterateWithSOR(zerosInitialGrid, unknownNodes, w, h, g, 50)

Current grid at iteration 49:
[[ -5.         -10.         -10.         -10.           5.        ]
 [  0.          -3.22792659  -1.6827877    4.31795635  20.        ]
 [  0.           0.07316468   3.046875     9.38864087  20.        ]
 [  0.           3.07787698   6.14459325  11.0577877   20.        ]
 [  5.          10.          10.          10.          15.        ]]


##w_opt = 1.729

In [ ]:
w = 1.729
iterateWithSOR(zerosInitialGrid, unknownNodes, w, h, g, 44)

Current grid at iteration 43:
[[ -5.         -10.         -10.         -10.           5.        ]
 [  0.          -3.22792082  -1.68277946   4.31795932  20.        ]
 [  0.           0.07317067   3.04688306   9.38864169  20.        ]
 [  0.           3.07787811   6.14459622  11.05777999  20.        ]
 [  5.          10.          10.          10.          15.        ]]


##w = 1.75

In [ ]:
w = 1.75
iterateWithSOR(zerosInitialGrid, unknownNodes, w, h, g, 44)

Current grid at iteration 43:
[[ -5.         -10.         -10.         -10.           5.        ]
 [  0.          -3.22790499  -1.6827603    4.31796354  20.        ]
 [  0.           0.07318419   3.04689771   9.38863797  20.        ]
 [  0.           3.07787866   6.14459827  11.0577581   20.        ]
 [  5.          10.          10.          10.          15.        ]]


##w = 2

In [ ]:
w = 2
iterateWithSOR(zerosInitialGrid, unknownNodes, w, h, g, 44)

Current grid at iteration 43:
[[ -5.         -10.         -10.         -10.           5.        ]
 [  0.           1.50039989   0.88095813   0.75389834  20.        ]
 [  0.           0.37885575   0.           1.19105139  20.        ]
 [  0.          -0.75389834   0.93925543   0.19466047  20.        ]
 [  5.          10.          10.          10.          15.        ]]


##w = 0.5

In [ ]:
w = 0.5
iterateWithSOR(zerosInitialGrid, unknownNodes, w, h, g, 44)

Current grid at iteration 43:
[[ -5.         -10.         -10.         -10.           5.        ]
 [  0.          -3.2285928   -1.68364099   4.31740989  20.        ]
 [  0.           0.07231139   3.04578209   9.38794097  20.        ]
 [  0.           3.07733053   6.14389335  11.05733948  20.        ]
 [  5.          10.          10.          10.          15.        ]]


##w = 2.5

In [ ]:
w = 2.5
iterateWithSOR(zerosInitialGrid, unknownNodes, w, h, g, 44)

Current grid at iteration 43:
[[-5.00000000e+00 -1.00000000e+01 -1.00000000e+01 -1.00000000e+01
   5.00000000e+00]
 [ 0.00000000e+00  1.11471793e+08  3.46262811e+08  2.46236245e+08
   2.00000000e+01]
 [ 0.00000000e+00  2.27514174e+08  5.90366481e+08  3.44219814e+08
   2.00000000e+01]
 [ 0.00000000e+00  1.00685360e+08  4.22141025e+08 -1.28762987e+08
   2.00000000e+01]
 [ 5.00000000e+00  1.00000000e+01  1.00000000e+01  1.00000000e+01
   1.50000000e+01]]


##Matrix Method

In [ ]:
coefficientsMatrix = np.array(
    [
     [-4,1,0,1,0,0,0,0,0],
     [1,0,0,-4,1,0,1,0,0],
     [0,0,0,1,0,0,-4,1,0],
     [1,-4,1,0,1,0,0,0,0],
     [0,1,0,1,-4,1,0,1,0],
     [0,0,0,0,1,0,1,-4,1],
     [0,1,-4,0,0,1,0,0,0],
     [0,0,1,0,1,-4,0,0,1],
     [0,0,0,0,0,1,0,1,-4]
    ]
)

RHS = np.array(
    [
     g(1,1,h) + 10,
     g(2,1,h),
     g(3,1,h) - 10,
     g(1,2,h) + 10,
     g(2,2,h),
     g(3,2,h) - 10,
     g(1,3,h) - 10,
     g(2,3,h) - 20,
     g(3,3,h) - 30
    ]
)

In [ ]:
V = np.dot(np.linalg.inv(coefficientsMatrix),RHS)
V

array([-3.22792659, -1.6827877 ,  4.31795635,  0.07316468,  3.046875  ,
        9.38864087,  3.07787698,  6.14459325, 11.0577877 ])

##Analytical Method

In [ ]:
va1 = 0
va2 = 0
h = 1/4

# Maximum value without causing an overflow error (decreasing)
I = 20
for N in range(I):
  n = 2*N+1
  # print(n)
  va1 += ((4*np.sinh(h*np.pi*n)/(np.pi*n*np.sinh(np.pi*n))))*(
      30*np.sin(h*np.pi*n)
      # + 20*np.sin(h*np.pi*n)
      - 10*np.sin((1-h)*np.pi*n)
  )

for M in range(1,I+1):
  for L in range(1,I+1):
    # print(M, L)
    # A = (((-1)**M)/((M**2+L**2)*np.pi**2)) * 144/(M*L*np.pi)
    A = 36*((-1)**M)*(((-1)**L+1) - 2)/(M*L*np.pi)
    va2 += A*np.sin(np.pi*M*h)*np.sin(np.pi*L*h)

print(va1)
print(va2)
print(va1+va2)

1.3594333622612327
7.578940235888788
8.93837359815002


In [ ]:
for i in range(1):
  print(i)

0


###Removing charge distribution (Laplace Equation)

In [ ]:
def GL(x,y,h):
  return 0

####SOR with w_opt = 1.729

In [ ]:
w = 1.729
iterateWithSOR(zerosInitialGrid, unknownNodes, w, h, GL, 44)

Current grid at iteration 43:
[[ -5.         -10.         -10.         -10.           5.        ]
 [  0.          -2.14285062  -0.53570585   5.0000028   20.        ]
 [  0.           1.96429195   5.00000765  10.5357146   20.        ]
 [  0.           5.00000029   8.03571574  12.14284785  20.        ]
 [  5.          10.          10.          10.          15.        ]]


####Matrix method

In [ ]:
RHSL = np.array(
    [
     GL(1,1,h) + 10,
     GL(2,1,h),
     GL(3,1,h) - 10,
     GL(1,2,h) + 10,
     GL(2,2,h),
     GL(3,2,h) - 10,
     GL(1,3,h) - 10,
     GL(2,3,h) - 20,
     GL(3,3,h) - 30
    ]
)

VL = np.dot(np.linalg.inv(coefficientsMatrix),RHSL)
VL

array([-2.14285714, -0.53571429,  5.        ,  1.96428571,  5.        ,
       10.53571429,  5.        ,  8.03571429, 12.14285714])

# Ex 3.3

##w = 1

In [ ]:
zerosInitialGrid33 = np.array(
    [
    [0,0,0,0],
    [0,0,0,10],
    [0,0,0,10],
    [0,0,0,0]
    ]
)

unknownNodes33 = [
    (1,1),(2,1),
    (1,2),(2,2)
]

h = 1/3

def g(x,y,h):
  return 0

##w = 1

In [ ]:
w = 1
iterateWithSOR(zerosInitialGrid33, unknownNodes33, w, h, g, 44)

Current grid at iteration 43:
[[ 0.    0.    0.    0.  ]
 [ 0.    1.25  3.75 10.  ]
 [ 0.    1.25  3.75 10.  ]
 [ 0.    0.    0.    0.  ]]


##w = 1.25

In [ ]:
w = 1.25
iterateWithSOR(zerosInitialGrid33, unknownNodes33, w, h, g, 44)

Current grid at iteration 43:
[[ 0.    0.    0.    0.  ]
 [ 0.    1.25  3.75 10.  ]
 [ 0.    1.25  3.75 10.  ]
 [ 0.    0.    0.    0.  ]]


##w = 1.5

In [ ]:
w = 1.5
iterateWithSOR(zerosInitialGrid33, unknownNodes33, w, h, g, 44)

Current grid at iteration 43:
[[ 0.    0.    0.    0.  ]
 [ 0.    1.25  3.75 10.  ]
 [ 0.    1.25  3.75 10.  ]
 [ 0.    0.    0.    0.  ]]


##w = 1.75

In [ ]:
w = 1.75
iterateWithSOR(zerosInitialGrid33, unknownNodes33, w, h, g, 44)

Current grid at iteration 43:
[[ 0.          0.          0.          0.        ]
 [ 0.          1.24999922  3.7500059  10.        ]
 [ 0.          1.25001386  3.75000127 10.        ]
 [ 0.          0.          0.          0.        ]]


##w = 2

In [ ]:
w = 2
iterateWithSOR(zerosInitialGrid33, unknownNodes33, w, h, g, 44)

Current grid at iteration 43:
[[ 0.   0.   0.   0. ]
 [ 0.   2.5  5.  10. ]
 [ 0.   5.   2.5 10. ]
 [ 0.   0.   0.   0. ]]


##w = 0.5

In [ ]:
w = 0.5
iterateWithSOR(zerosInitialGrid33, unknownNodes33, w, h, g, 44)

Current grid at iteration 43:
[[ 0.          0.          0.          0.        ]
 [ 0.          1.24999902  3.74999917 10.        ]
 [ 0.          1.24999917  3.7499993  10.        ]
 [ 0.          0.          0.          0.        ]]


##w = 2.5

In [ ]:
w = 2.5
iterateWithSOR(zerosInitialGrid33, unknownNodes33, w, h, g, 44)

Current grid at iteration 43:
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -2.38154525e+07  6.97653768e+07  1.00000000e+01]
 [ 0.00000000e+00  2.09709736e+08  7.04507648e+07  1.00000000e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]
